---
# file: grafana/tasks/main.yml
#
# tasks file
#

- name: include OS family/distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "../defaults/{{ ansible_os_family | lower }}-{{ ansible_distribution | lower }}_{{ ansible_distribution_version | lower }}.yml"
    - "../defaults/{{ ansible_os_family | lower }}-{{ ansible_distribution | lower }}.yml"
    - "../defaults/{{ ansible_os_family | lower }}.yml"

- include: debug.yml
  when: debug | default(false)
  tags: debug

- include: validation.yml
  tags: validation

- name: ensure apt dependencies are installed
  apt:
    name="{{ item }}"
    state=present
  become: yes
  when: ansible_distribution | lower == 'debian' and grafana_apt_dependencies is defined
  with_items: "{{ grafana_apt_dependencies }}"

- name: Add packagecloud.io repository key
  apt_key:
    url: "https://packagecloud.io/gpg.key"
    state: present

- name: Add packagecloud.io repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb https://packagecloud.io/grafana/stable/debian/ jessie main"

- name: Install Grafana
  apt:
    name: "grafana"
    state: present

- name: Install grafana plugins
  shell: "grafana-cli plugins install {{ item }}"
  with_items: "{{ grafana_plugins }}"
  notify: restart grafana

- name: ensure integrity of grafana configuration
  template:
    src=etc/grafana/grafana.ini.j2
    dest="{{ grafana_conf_file }}"
    owner="{{ grafana_user }}"
    group="{{ grafana_group }}"
    mode=0644
  become: yes
  notify: restart grafana

- name: Enable Grafana
  systemd:
    name: grafana-server
    state: started
    enabled: True